### ISSUE TITLE
Don't match groups without words when choosing (highest) punishment

### ISSUE THREAD

**Issue by greenbigfrog** [TheCodingDen/mini-slash#3]

**Comment by greenbigfrog** [comment]
Actually, slightly wrong description:
Don't match groups without words when choosing (highest) punishment

**Comment by kantenkugel** [comment]
you know that you can change that, right? xD

**Comment by kantenkugel** [comment]
might be an issue of this one:
https://github.com/TheCodingDen/mini-slash/blob/49972bcdd721f8795a1c38efbd2ff9567bc6902c/src/slash.cr#L73-L86
`word` variable is not reset when there is no word in the current group -> the if at the end of the loop still matches
